version: '3.1'

services:
  mongo-master:
    image:  mongo:latest
    container_name: goexercise-mongo-master
    restart: always
    ports:
      - "27017:27017"
    command: "--bind_ip_all --replSet rs0 --port 27017"

  mongo-slave-1:
    image:  mongo:latest
    container_name: goexercise-mongo-slave-1
    restart: always
    ports:
      - "27018:27018"
    command: "--bind_ip_all --replSet rs0 --port 27018"

  mongo-express:
    image: mongo-express:latest
    container_name: goexercise-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-slave-1:27018/?replicaSet=rs0


# enter the mongo master terminal
# run mongosh
# run rs.initiate({"_id":"rs0","members":[{"_id":0,"host":"mongo-master:27017"},{"_id":1,"host":"mongo-slave-1:27018"}]});
